import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { lstat, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { verifyBirth, _birthVerifierInternals } from "./verify-birth.mjs";
import { _birthInternals } from "./run-birth.mjs";

const branch = "poiesis/v1-birth-release-steward";
const repository = "tkersey/poiesis";
const changedPaths = _birthInternals.expectedChangedPaths;
const sha256 = (value) => createHash("sha256").update(value).digest("hex");

function command(executable, args, options = {}) {
  const result = Bun.spawnSync([executable, ...args], { cwd: options.cwd, env: options.env, stdout: "pipe", stderr: "pipe" });
  const stdout = result.stdout ? Buffer.from(result.stdout) : Buffer.alloc(0);
  const stderr = result.stderr ? Buffer.from(result.stderr) : Buffer.alloc(0);
  if (result.error || (!options.allowFailure && result.exitCode !== 0)) throw new Error(`${executable} ${args.join(" ")} failed\n${result.error ?? ""}${stdout}${stderr}`);
  return Object.freeze({ status: result.exitCode, stdout, stderr });
}

function gitEnvironment() {
  const environment = { ...process.env };
  for (const name of ["GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_OBJECT_DIRECTORY", "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_REPLACE_REF_BASE"]) delete environment[name];
  environment.GIT_CONFIG_NOSYSTEM = "1";
  environment.GIT_NO_REPLACE_OBJECTS = "1";
  environment.GIT_TERMINAL_PROMPT = "0";
  return environment;
}

export function assertPoiesisRemote(value) {
  assert.match(value, /^(?:https:\/\/github\.com\/tkersey\/poiesis(?:\.git)?|git@github\.com:tkersey\/poiesis(?:\.git)?)$/);
  return value;
}

export function birthPullRequestBody(value) {
  return [
    "Generated by authenticated frozen Praxis v1.0.6. This draft requires ordinary human review.",
    "",
    `Parent candidate: \`${value.parentCandidateCommit}\``,
    `Parent application: \`${value.parentApplicationId}\``,
    `Scaffold commit: \`${value.scaffoldCommit}\``,
    `Verified diff SHA-256: \`${value.diffSha256}\``,
    `Birth receipt SHA-256: \`${value.birthReceiptSha256}\``,
    `Independent verification SHA-256: \`${value.verificationDigest}\``,
  ].join("\n");
}

export function buildPublicationRecord(value) {
  for (const digest of [value.parentApplicationId, value.diffSha256, value.birthReceiptSha256, value.verificationDigest]) assert.match(digest, /^[0-9a-f]{64}$/);
  for (const commit of [value.parentCandidateCommit, value.scaffoldCommit, value.publishedHead, value.publishedTree]) assert.match(commit, /^[0-9a-f]{40}$/);
  assert.ok(Number.isInteger(value.pullRequest.number) && value.pullRequest.number > 0);
  assert.match(value.pullRequest.url, /^https:\/\/github\.com\/tkersey\/poiesis\/pull\/[1-9][0-9]*$/);
  assert.equal(value.pullRequest.isDraft, true); assert.equal(value.pullRequest.headRefOid, value.publishedHead); assert.equal(value.pullRequest.baseRefName, "main");
  return Object.freeze({
    format: "poiesis-birth-publication/v1",
    repository,
    branch,
    base_revision: value.scaffoldCommit,
    parent_candidate_commit: value.parentCandidateCommit,
    parent_application_id: value.parentApplicationId,
    birth_receipt_sha256: value.birthReceiptSha256,
    independent_verification_sha256: value.verificationDigest,
    verified_diff_sha256: value.diffSha256,
    pull_request_number: value.pullRequest.number,
    pull_request_url: value.pullRequest.url,
    draft: value.pullRequest.isDraft,
    published_head: value.publishedHead,
    published_tree: value.publishedTree,
    published_tree_matches_verified_diff: true,
  });
}

async function verifyFileDigests(worktree, expected) {
  const actual = {};
  for (const path of changedPaths) actual[path] = sha256(await readFile(join(worktree, path)));
  assert.deepEqual(actual, expected, "publication changed verified file bytes");
}

export async function publishBirth(options) {
  const verified = await verifyBirth(options);
  const { record } = verified; const worktree = verified.worktree; const environment = gitEnvironment();
  const remote = command("git", ["remote", "get-url", "origin"], { cwd: options.repositoryRoot, env: environment }).stdout.toString("utf8").trim();
  assertPoiesisRemote(remote);
  assert.equal(command("git", ["show-ref", "--verify", `refs/heads/${branch}`], { cwd: worktree, env: environment, allowFailure: true }).status, 1, "birth branch already exists");
  assert.equal(command("git", ["ls-remote", "--exit-code", "--heads", "origin", branch], { cwd: worktree, env: environment, allowFailure: true }).status, 2, "remote birth branch lookup failed or branch already exists");
  command("git", ["switch", "--create", branch], { cwd: worktree, env: environment });
  command("git", ["add", "--", ...changedPaths], { cwd: worktree, env: environment });
  const stagedPaths = command("git", ["diff", "--cached", "--name-only", "--diff-filter=ACDMRTUXB"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim().split("\n").filter(Boolean);
  assert.deepEqual(stagedPaths, changedPaths, "staged birth path set drifted");
  const stagedDiff = command("git", ["diff", "--cached", "--binary", "--no-ext-diff", "--full-index", record.scaffold_commit, "--", ...changedPaths], { cwd: worktree, env: environment }).stdout;
  assert.equal(sha256(stagedDiff), record.final_diff_sha256, "staged birth diff drifted");
  command("git", ["-c", "core.hooksPath=/dev/null", "-c", "user.name=Agent Poiesis Receiver", "-c", "user.email=poiesis@users.noreply.github.com", "commit", "--no-gpg-sign", "--message", "Generate Release Steward with frozen Praxis"], { cwd: worktree, env: environment });
  const publishedHead = command("git", ["rev-parse", "HEAD"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim();
  const publishedTree = command("git", ["rev-parse", "HEAD^{tree}"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim();
  assert.equal(command("git", ["rev-parse", "HEAD^"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim(), record.scaffold_commit);
  assert.equal(command("git", ["status", "--porcelain=v1", "--untracked-files=all"], { cwd: worktree, env: environment }).stdout.length, 0, "published birth worktree is dirty");
  await verifyFileDigests(worktree, record.terminal_file_digests);
  command("git", ["push", "--porcelain", "--set-upstream", "origin", branch], { cwd: worktree, env: environment });

  const birthReceiptSha256 = sha256(await readFile(options.receipt));
  const body = birthPullRequestBody({ parentCandidateCommit: record.parent_candidate_commit, parentApplicationId: record.parent_application_id, scaffoldCommit: record.scaffold_commit, diffSha256: record.final_diff_sha256, birthReceiptSha256, verificationDigest: verified.verificationDigest });
  command("gh", ["pr", "create", "--repo", repository, "--base", "main", "--head", branch, "--draft", "--title", "Generate Release Steward with frozen Praxis", "--body", body], { cwd: options.repositoryRoot, env: environment });
  const pullRequest = JSON.parse(command("gh", ["pr", "view", branch, "--repo", repository, "--json", "number,url,isDraft,headRefOid,baseRefName,state"], { cwd: options.repositoryRoot, env: environment }).stdout.toString("utf8"));
  assert.equal(pullRequest.state, "OPEN");
  const publication = buildPublicationRecord({ parentCandidateCommit: record.parent_candidate_commit, parentApplicationId: record.parent_application_id, scaffoldCommit: record.scaffold_commit, diffSha256: record.final_diff_sha256, birthReceiptSha256, verificationDigest: verified.verificationDigest, publishedHead, publishedTree, pullRequest });
  const publicationPath = join(options.repositoryRoot, "conformance/poiesis-v1/receipts/birth.publication.json");
  try { await lstat(publicationPath); throw new Error("birth publication receipt already exists"); } catch (error) { if (error?.code !== "ENOENT") throw error; }
  await writeFile(publicationPath, `${JSON.stringify(publication, null, 2)}\n`, { flag: "wx", mode: 0o644 });
  return Object.freeze({ publication, publicationPath });
}

if (import.meta.main) {
  const options = _birthVerifierInternals.parseArgs(process.argv.slice(2));
  if (options.fixture) throw new Error("birth publication does not accept fixtures");
  const result = await publishBirth(options);
  process.stdout.write(`poiesis_birth_publication=${result.publicationPath}\npoiesis_birth_pr=${result.publication.pull_request_url}\n`);
}

export const _birthPublicationInternals = Object.freeze({ branch });
