import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { lstat, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { verifyChild, _childVerifierInternals } from "./verify-child.mjs";

const sha256 = (value) => createHash("sha256").update(value).digest("hex");

function command(executable, args, options = {}) {
  const result = Bun.spawnSync([executable, ...args], { cwd: options.cwd, env: options.env, stdout: "pipe", stderr: "pipe" }); const stdout = result.stdout ? Buffer.from(result.stdout) : Buffer.alloc(0); const stderr = result.stderr ? Buffer.from(result.stderr) : Buffer.alloc(0);
  if (result.error || (!options.allowFailure && result.exitCode !== 0)) throw new Error(`${executable} ${args.join(" ")} failed\n${result.error ?? ""}${stdout}${stderr}`);
  return Object.freeze({ status: result.exitCode, stdout, stderr });
}

function gitEnvironment() { const environment = { ...process.env }; for (const name of ["GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_OBJECT_DIRECTORY", "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_REPLACE_REF_BASE"]) delete environment[name]; environment.GIT_CONFIG_NOSYSTEM = "1"; environment.GIT_NO_REPLACE_OBJECTS = "1"; environment.GIT_TERMINAL_PROMPT = "0"; return environment; }

export function taskSlug(targetVersion, taskSha256) {
  const version = String(targetVersion).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 32) || "release";
  assert.match(taskSha256, /^[0-9a-f]{64}$/);
  return `${version}-${taskSha256.slice(0, 12)}`;
}

export function assertTargetRemote(value, repository) {
  const escaped = repository.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  assert.match(value, new RegExp(`^(?:https://github\\.com/${escaped}(?:\\.git)?|git@github\\.com:${escaped}(?:\\.git)?)$`));
  return value;
}

export function childPullRequestBody(value) {
  return ["Generated by the byte-frozen Agent Poiesis Release Steward. This draft requires ordinary human review.", "", `Parent candidate: \`${value.parentCandidateCommit}\``, `Child candidate SHA-256: \`${value.childCandidateSha256}\``, `Child application: \`${value.applicationId}\``, `Child live receipt SHA-256: \`${value.liveReceiptSha256}\``, `Verified diff SHA-256: \`${value.diffSha256}\``, `Independent verification SHA-256: \`${value.verificationDigest}\``].join("\n");
}

export function buildChildPublicationRecord(value) {
  for (const digest of [value.childCandidateSha256, value.applicationId, value.liveReceiptSha256, value.diffSha256, value.verificationDigest]) assert.match(digest, /^[0-9a-f]{64}$/);
  for (const commit of [value.parentCandidateCommit, value.baseRevision, value.publishedHead, value.publishedTree]) assert.match(commit, /^[0-9a-f]{40}$/);
  assert.equal(value.pullRequest.isDraft, true); assert.equal(value.pullRequest.headRefOid, value.publishedHead); assert.ok(Number.isInteger(value.pullRequest.number) && value.pullRequest.number > 0);
  assert.equal(value.pullRequest.url, `https://github.com/${value.repository}/pull/${value.pullRequest.number}`);
  return Object.freeze({ format: "poiesis-child-publication/v1", repository: value.repository, branch: value.branch, base_revision: value.baseRevision, parent_candidate_commit: value.parentCandidateCommit, child_candidate_sha256: value.childCandidateSha256, application_id: value.applicationId, child_live_receipt_sha256: value.liveReceiptSha256, independent_verification_sha256: value.verificationDigest, verified_diff_sha256: value.diffSha256, pull_request_number: value.pullRequest.number, pull_request_url: value.pullRequest.url, draft: value.pullRequest.isDraft, published_head: value.publishedHead, published_tree: value.publishedTree, published_tree_matches_verified_diff: true });
}

async function verifyFileDigests(worktree, expected) { const actual = {}; for (const path of Object.keys(expected).sort()) actual[path] = sha256(await readFile(join(worktree, path))); assert.deepEqual(actual, expected); }

export async function publishChild(options) {
  const verified = await verifyChild(options); const receipt = JSON.parse(await readFile(options.receipt, "utf8")); assert.equal(receipt.independent_verifier_passed, true);
  const goal = JSON.parse(await readFile(options.goal, "utf8")); const branch = `poiesis/v1-release-steward-${taskSlug(goal.target_version, receipt.task_sha256)}`; const environment = gitEnvironment(); const worktree = verified.worktree;
  const remote = command("git", ["remote", "get-url", "origin"], { cwd: options.targetRoot, env: environment }).stdout.toString("utf8").trim(); assertTargetRemote(remote, options.repository);
  assert.equal(command("git", ["show-ref", "--verify", `refs/heads/${branch}`], { cwd: worktree, env: environment, allowFailure: true }).status, 1);
  assert.equal(command("git", ["ls-remote", "--exit-code", "--heads", "origin", branch], { cwd: worktree, env: environment, allowFailure: true }).status, 2);
  command("git", ["switch", "--create", branch], { cwd: worktree, env: environment }); command("git", ["add", "--", ...verified.record.changed_paths], { cwd: worktree, env: environment });
  const staged = command("git", ["diff", "--cached", "--name-only", "--diff-filter=ACDMRTUXB"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim().split("\n").filter(Boolean); assert.deepEqual(staged, verified.record.changed_paths);
  const diff = command("git", ["diff", "--cached", "--binary", "--no-ext-diff", "--full-index", options.baseRevision, "--", ...staged], { cwd: worktree, env: environment }).stdout; assert.equal(sha256(diff), verified.record.final_diff_sha256);
  command("git", ["-c", "core.hooksPath=/dev/null", "-c", "user.name=Agent Poiesis Receiver", "-c", "user.email=poiesis@users.noreply.github.com", "commit", "--no-gpg-sign", "--message", `Reconcile release ${goal.target_version} with Agent Poiesis`], { cwd: worktree, env: environment });
  const publishedHead = command("git", ["rev-parse", "HEAD"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim(); const publishedTree = command("git", ["rev-parse", "HEAD^{tree}"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim(); assert.equal(command("git", ["rev-parse", "HEAD^"], { cwd: worktree, env: environment }).stdout.toString("utf8").trim(), options.baseRevision); assert.equal(command("git", ["status", "--porcelain=v1", "--untracked-files=all"], { cwd: worktree, env: environment }).stdout.length, 0); await verifyFileDigests(worktree, verified.record.terminal_file_digests);
  command("git", ["push", "--porcelain", "--set-upstream", "origin", branch], { cwd: worktree, env: environment });
  const baseBranch = command("gh", ["repo", "view", options.repository, "--json", "defaultBranchRef", "--jq", ".defaultBranchRef.name"], { cwd: options.poiesisRoot, env: environment }).stdout.toString("utf8").trim(); assert.match(baseBranch, /^[A-Za-z0-9._/-]+$/);
  const [candidate, parentLock] = await Promise.all([JSON.parse(await readFile(options.candidate, "utf8")), JSON.parse(await readFile(join(options.poiesisRoot, "conformance/poiesis-v1/parent.lock.json"), "utf8"))]); assert.equal(candidate.application_id, receipt.application_id); const parentCandidateCommit = parentLock.release.candidateCommit; const liveReceiptSha256 = sha256(await readFile(options.receipt)); const body = childPullRequestBody({ parentCandidateCommit, childCandidateSha256: receipt.child_candidate_sha256, applicationId: receipt.application_id, liveReceiptSha256, diffSha256: receipt.final_diff_sha256, verificationDigest: verified.verificationDigest });
  command("gh", ["pr", "create", "--repo", options.repository, "--base", baseBranch, "--head", branch, "--draft", "--title", `Reconcile release ${goal.target_version} with Agent Poiesis`, "--body", body], { cwd: options.poiesisRoot, env: environment });
  const pullRequest = JSON.parse(command("gh", ["pr", "view", branch, "--repo", options.repository, "--json", "number,url,isDraft,headRefOid,baseRefName,state"], { cwd: options.poiesisRoot, env: environment }).stdout.toString("utf8")); assert.equal(pullRequest.state, "OPEN"); assert.equal(pullRequest.baseRefName, baseBranch);
  const publication = buildChildPublicationRecord({ repository: options.repository, branch, baseRevision: options.baseRevision, parentCandidateCommit, childCandidateSha256: receipt.child_candidate_sha256, applicationId: receipt.application_id, liveReceiptSha256, diffSha256: receipt.final_diff_sha256, verificationDigest: verified.verificationDigest, publishedHead, publishedTree, pullRequest });
  const path = join(options.poiesisRoot, "conformance/poiesis-v1/receipts/child.publication.json"); try { await lstat(path); throw new Error("child publication receipt already exists"); } catch (error) { if (error?.code !== "ENOENT") throw error; } await writeFile(path, `${JSON.stringify(publication, null, 2)}\n`, { flag: "wx", mode: 0o644 }); return Object.freeze({ publication, path });
}

if (import.meta.main) { const options = _childVerifierInternals.parseArgs(process.argv.slice(2)); const result = await publishChild(options); process.stdout.write(`poiesis_child_publication=${result.path}\npoiesis_child_pr=${result.publication.pull_request_url}\n`); }
